services:
  grocy-assistant:
    image: ghcr.io/snksqldba88/grocy-assistant::latest
    container_name: grocy-assistant
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8086:8080"
